package inject

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	// Markers delimit the CodeRank-managed section in shared files
	// like .windsurfrules or AGENTS.md that may contain other content.
	markerStart = "<!-- coderank:start -->"
	markerEnd   = "<!-- coderank:end -->"
)

// ContextContent holds the formatted content to write into an agent's context file.
type ContextContent struct {
	// Libraries lists each library's name and version for the header comment.
	Libraries []string

	// Body is the concatenated API surfaces, formatted as markdown.
	Body string

	// TotalTokens is the estimated token count of the body.
	TotalTokens int
}

// WriteContext writes the CodeRank context into the agent's file at the given
// path (relative to projectDir). For files that may contain other content
// (AGENTS.md, .windsurfrules), it uses markers to replace only the CodeRank
// section. For dedicated files (.claude/context/..., .cursor/rules/...),
// it overwrites the entire file.
func WriteContext(projectDir string, agent Agent, content ContextContent) error {
	fullPath := filepath.Join(projectDir, agent.ContextPath)

	// Ensure parent directory exists
	if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
		return fmt.Errorf("creating directory for %s: %w", agent.ContextPath, err)
	}

	header := formatHeader(content.Libraries, content.TotalTokens)
	fullContent := header + content.Body

	// For shared files (AGENTS.md, .windsurfrules), use marker-based replacement
	if agent.Name == "Codex" || agent.Name == "Windsurf" {
		return writeMarkerSection(fullPath, fullContent)
	}

	// For dedicated files, write the entire content
	return os.WriteFile(fullPath, []byte(fullContent), 0644)
}

// formatHeader generates the comment header that appears at the top of
// every injected context file. It documents what the file is, when it was
// updated, and how to get deeper docs.
func formatHeader(libraries []string, totalTokens int) string {
	return fmt.Sprintf(
		`%s
<!-- Auto-generated by coderank inject. Do not edit manually. -->
<!-- Last updated: %s | Stack: %s | ~%d tokens -->
<!-- For detailed docs on any topic, run: coderank fetch "<topic>" --raw -->

`,
		markerStart,
		time.Now().Format("2006-01-02 15:04"),
		strings.Join(libraries, ", "),
		totalTokens,
	)
}

// writeMarkerSection replaces the content between coderank markers in a file.
// If the file doesn't exist or has no markers, appends a new marked section.
func writeMarkerSection(path, content string) error {
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("reading %s: %w", path, err)
	}

	markedContent := content + "\n" + markerEnd + "\n"

	if len(existing) == 0 {
		// New file — just write the marked content
		return os.WriteFile(path, []byte(markedContent), 0644)
	}

	existingStr := string(existing)
	before, rest, found := strings.Cut(existingStr, markerStart)
	if !found {
		// No existing markers — append at the end
		return os.WriteFile(path, []byte(existingStr+"\n"+markedContent), 0644)
	}

	_, after, found := strings.Cut(rest, markerEnd)
	if !found {
		// Start marker but no end marker — append at the end
		return os.WriteFile(path, []byte(existingStr+"\n"+markedContent), 0644)
	}

	// Replace existing section
	return os.WriteFile(path, []byte(before+markedContent+after), 0644)
}
