package inject

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/coderank-dev/coderank/internal/agents"
)

// ContextContent holds the formatted content to write into an agent's context file.
type ContextContent struct {
	// Libraries lists each library's name and version for the header comment.
	Libraries []string

	// Body is the concatenated API surfaces, formatted as markdown.
	Body string

	// TotalTokens is the estimated token count of the body.
	TotalTokens int
}

// WriteContext writes the CodeRank context into the agent's inject file.
// Dispatch is data-driven from the agent's project format:
//
//   - FormatSingleMarkerFile (Codex, Windsurf, etc.): marker-based replacement
//     so content written by the user or other tools is preserved.
//   - Other formats (or Generic): overwrite the file wholesale since the
//     target is coderank-owned (e.g. .claude/context/coderank-stack.md).
func WriteContext(projectDir string, agent agents.Agent, content ContextContent) error {
	contextPath := agent.InjectContextPath()
	if contextPath == "" {
		return fmt.Errorf("inject not supported for %s", agent.Name)
	}
	fullPath := filepath.Join(projectDir, contextPath)

	if err := os.MkdirAll(filepath.Dir(fullPath), 0755); err != nil {
		return fmt.Errorf("creating directory for %s: %w", contextPath, err)
	}

	header := formatHeader(content.Libraries, content.TotalTokens)
	body := header + content.Body

	if agent.Project.Format == agents.FormatSingleMarkerFile {
		return agents.WriteMarkerSection(fullPath, body)
	}

	return os.WriteFile(fullPath, []byte(body), 0644)
}

// formatHeader generates the comment header that appears at the top of every
// injected context file. It documents what the file is, when it was updated,
// and how to get deeper docs.
func formatHeader(libraries []string, totalTokens int) string {
	return fmt.Sprintf(
		`<!-- Auto-generated by coderank inject. Do not edit manually. -->
<!-- Last updated: %s | Stack: %s | ~%d tokens -->
<!-- For detailed docs on any topic, run: coderank query <lib> "<question>" --raw -->

`,
		time.Now().Format("2006-01-02 15:04"),
		strings.Join(libraries, ", "),
		totalTokens,
	)
}
